# Generated by Django 2.1.7 on 2019-04-20 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adm_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='father_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatherN', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='father_name',
            name='std_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.Id'),
        ),
        migrations.AddField(
            model_name='adm_date',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.father_name'),
        ),
    ]
