# Generated by Django 2.2.5 on 2019-09-30 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190420_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('child_id', models.IntegerField(primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('Paent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('parent_fn', models.CharField(max_length=20)),
                ('parent_ln', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('profession', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='father_name',
            name='std_id',
        ),
        migrations.DeleteModel(
            name='adm_date',
        ),
        migrations.DeleteModel(
            name='father_name',
        ),
        migrations.DeleteModel(
            name='Id',
        ),
        migrations.AddField(
            model_name='child',
            name='child_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Parent'),
        ),
    ]
