# Generated by Django 2.2.5 on 2019-09-30 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20190930_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='promotedGrade',
            fields=[
                ('grade_id', models.IntegerField(primary_key=True, serialize=False)),
                ('grade_name', models.CharField(max_length=10)),
                ('child_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Child')),
            ],
        ),
    ]
