# Generated by Django 2.2.5 on 2019-09-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_promotedgrade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='promotedGrade',
        ),
    ]
